services:
  llamactl-llamacpp:
    build:
      context: ..
      dockerfile: docker/Dockerfile.llamacpp.vulkan
    image: llamactl:llamacpp-vulkan
    container_name: llamactl-llamacpp
    ports:
      - "8000:8080"
    volumes:
      - ${HOST_MODELS_DIR}:/models  # Models directory
      - ${HOST_HF_CACHE}:/root/.cache/huggingface
      - ${HOST_CACHE_DIR}:/root/.cache  # Llama.cpp cache
      - ${HOST_DATA_DIR}:/root/.local/share/llamactl
    environment:
      # Set data directory for persistence
      #- LLAMACTL_DATA_DIR=/data
      # Enable Docker mode for nested containers
      - LLAMACTL_LLAMACPP_DOCKER_ENABLED=${LLAMACTL_LLAMACPP_DOCKER_ENABLED}
      - LLAMACTL_REQUIRE_INFERENCE_AUTH=${LLAMACTL_REQUIRE_INFERENCE_AUTH}
      - LLAMACTL_REQUIRE_MANAGEMENT_AUTH=${LLAMACTL_REQUIRE_MANAGEMENT_AUTH}
    devices:
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    ulimits:
      memlock: -1
    restart: unless-stopped